static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         AerotechAxisStateMachine.cpp
//
// description :  C++ source for the AerotechAxis and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author: jean_coquet $
//
// $Revision: 1.2 $
// $Date: 2012/03/02 15:45:13 $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source: /cvsroot/tango-ds/Motion/Aerotech/src/AerotechAxisStateMachine.cpp,v $
// $Log: AerotechAxisStateMachine.cpp,v $
// Revision 1.2  2012/03/02 15:45:13  jean_coquet
// mise au point avec le materiel
//
// Revision 1.1  2012/02/23 17:46:18  olivierroux
// - initial import #21894
//
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <AerotechAxis.h>
#include <AerotechAxisClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace AerotechAxis_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_position_allowed
// 
// description : 	Read/Write allowed for position attribute.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_position_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_offset_allowed
// 
// description : 	Read/Write allowed for offset attribute.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_offset_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_velocity_allowed
// 
// description : 	Read/Write allowed for velocity attribute.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_velocity_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_isBrakeOn_allowed
// 
// description : 	Read/Write allowed for isBrakeOn attribute.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_isBrakeOn_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_relativeMove_allowed
// 
// description : 	Read/Write allowed for relativeMove attribute.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_relativeMove_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_Stop_allowed
// 
// description : 	Execution allowed for Stop command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_Stop_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_InitializeReferencePosition_allowed
// 
// description : 	Execution allowed for InitializeReferencePosition command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_InitializeReferencePosition_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_BrakeON_allowed
// 
// description : 	Execution allowed for BrakeON command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_BrakeON_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_BrakeOFF_allowed
// 
// description : 	Execution allowed for BrakeOFF command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_BrakeOFF_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_FaultAck_allowed
// 
// description : 	Execution allowed for FaultAck command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_FaultAck_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_Enable_allowed
// 
// description : 	Execution allowed for Enable command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_Enable_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AerotechAxis::is_Disable_allowed
// 
// description : 	Execution allowed for Disable command.
//
//-----------------------------------------------------------------------------
bool AerotechAxis::is_Disable_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace AerotechAxis_ns
