static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         EnsembleExpertStateMachine.cpp
//
// description :  C++ source for the EnsembleExpert and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <EnsembleExpert.h>
#include <EnsembleExpertClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace EnsembleExpert_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_currentVelocity_allowed
// 
// description : 	Read/Write allowed for currentVelocity attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_currentVelocity_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_lowLimit_allowed
// 
// description : 	Read/Write allowed for lowLimit attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_lowLimit_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_highLimit_allowed
// 
// description : 	Read/Write allowed for highLimit attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_highLimit_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_homeVelocity_allowed
// 
// description : 	Read/Write allowed for homeVelocity attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_homeVelocity_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_homeOffset_allowed
// 
// description : 	Read/Write allowed for homeOffset attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_homeOffset_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_statusRaw_allowed
// 
// description : 	Read/Write allowed for statusRaw attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_statusRaw_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_errorRaw_allowed
// 
// description : 	Read/Write allowed for errorRaw attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_errorRaw_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_positionError_allowed
// 
// description : 	Read/Write allowed for positionError attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_positionError_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_rampRate_allowed
// 
// description : 	Read/Write allowed for rampRate attribute.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_rampRate_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		EnsembleExpert::is_Reset_allowed
// 
// description : 	Execution allowed for Reset command.
//
//-----------------------------------------------------------------------------
bool EnsembleExpert::is_Reset_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace EnsembleExpert_ns
